### ISSUE TITLE
Music doesn't start in mountain biomes

### ISSUE THREAD

**Issue by PeterTheSalmon** [magneticflux-/fabric-start-the-music#7]
When attempting to start the music in the new mountain biomes, nothing happens.

**Comment by magneticflux-** [comment]
Hmm... I've been using it on my personal world and it seems to be working, but I might not know all the new music.

Do other music tracks play in other biomes, or does nothing happen at all?

**Comment by PeterTheSalmon** [comment]
In other biomes everything works as expected.

I've done some more investigation, and, strangely, this seems to only be a problem on one server. Loading the mod in singleplayer and testing it in new mountains works fine. The server was updated from 1.17, so maybe that makes a difference?

**Comment by magneticflux-** [comment]
I updated my own server from 1.17 and everything seems to be working. Is there anything in the logs? Does the F3 menu say you're in the right biome?

**Comment by magneticflux-** [comment]
I did a quick trace of the music source to verify nothing has changed in 1.18 that would break the mod and everything seems to be correct still.

When the mod is triggered, it sets the `timeUntilNextSong` value to 0 which forces a song to start. The song that is started is picked using `MinecraftClient#getMusicType`, which has checks for the credits, the Ender Dragon fight, underwater music, creative mode music, and finally biome-specific music. The biome-specific music is read from the biome that the player is currently in, and it is added to the biome in the `OverworldBiomeCreator` class, an example of which is in the `createSnowySlopes` method that sets the music to be `SoundEvents.MUSIC_OVERWORLD_SNOWY_SLOPES`.

**Comment by PeterTheSalmon** [comment]
Sorry for the slow reply - was away for Christmas.

I can basically see no reason why it isn't working - there are no console errors, no mod conflicts, and it works perfectly in every other situation. Upon further experimentation, music never plays in these mountains even if I just wait for hours, so I am forced to assume it is either a Paper bug or an unfixable Minecraft bug, and not a mod issue as I initially thought.

Thanks for your help - I'll leave an update if I find any conclusions.

**Comment by PeterTheSalmon** [comment]
Finally figured it out. Had nothing to do with mods, was simply corrupted game files. Reinstalling the instance fixed everything. Sorry for the trouble, and thanks for the great mod!
